### ISSUE TITLE
2.0 NPM package is missing the code

### ISSUE THREAD

**Issue by jelling** [codeably-io/jest-ai#16] opened 2024-06-05 20:35 UTC
The `2.0` release on NPM is missing the `dist` directory. So `npm` can't install it and `pnpm` appears to install it but then the export is empty.

**Comment by ranst91** [comment] 2024-06-05 20:37
Thanks for flagging it. Weird. I will take care of it soon!

**Comment by jelling** [comment] 2024-06-05 21:10
Thanks. I worked around it for the moment but linking from a local directory.

While I have you though, I'm having another odd issue:

![image](https://github.com/codeably-io/jest-ai/assets/1887486/079ea53a-9fc4-4277-9f40-a4dfe910cc68)

What's happening is that `.toSemanticallyMatch` is found but `.toSatisfyStatement` is not. And it's not just the VSCode TS Server as when I run the test it errors for `toSatisfyStatement`. And it doesn't error for `toSemanticallyMatch` but it also doesn't appear to do anything.

Fwiw I have this issue both with `2.0` and with `1.1.0`.

**Comment by ranst91** [comment] 2024-06-07 12:57
The releases are a bit wonky. It seems like the sentence satisfy matcher was missing from the types declarations.
I added the missing type and also release version 2.0.1.

If the issue is not resolved for you in the new version, LMK.
Closing for now

**Closed as completed by ranst91** 2024-06-07 12:57 UTC
